"CREATE TABLE ", "Authors", "author_id ", "author_name"
"CREATE TABLE", "Books", "book_id PRIMARY KEY" "title", "author_id", "price", "publication_date"
"CREATE TABLE", "Customers", "customer_id PRIMARY KEY", "customer_name VARCHAR(215)", "email VARCHAR(215)", "address TEXT"
"CREATE TABLE", "Orders", "order_id INT", "customer_id INT", "FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)", "order_date DATE"
"CREATE TABLE", "Order_details", "orderdetail INT", "order_id INT", "book_id INT", "quantity DOUBLE", "FOREIGN KEY (order_id) REFERENCES Orders(order_id), FOREIGN KEY (book_id) REFERENCES Books(book_id)"