"CREATE TABLE ", "Authors", "author_id ", "author_name"
"CREATE TABLE", "Books", "book_id PRIMARY KEY" "title", "author_id", "price", "publication_date"
"CREATE TABLE", "Customers", "customer_id PRIMARY KEY", "customer_name VARCHAR(215)", "email VARCHAR(215)", "address TEXT"
"CREATE TABLE", "Orders", "order_id PRIMARY KEY", "customer_id FOREIGN KEY", "order_date DATE"
"CREATE TABLE", "Order_details", "orderdetail PRIMARY KEY", "order_id FOREIGN KEY", "book_id FOREIGN KEY", "quantity DOUBLE"